### ISSUE TITLE
I want the event after the scroll end.

### ISSUE THREAD

**Issue by gomo** [adityamr15/react-native-wheel-picker-expo#5]
Hi @adityamr15 .

This product is simple and wonderful.  I am going to use this in my product for Datepicker.

The current onChange event is called repeatedly after each scroll, so I would like an event that is called after the end of the scroll for performance purposes.

It would be possible to achieve this by passing `onScrollEndDrag` to `flatListProps`, but I wanted to implement it here because it would duplicate the process of getting the selected item.

I tried it and was able to implement it, but can I send a pull request?

**Comment by gomo** [comment]
Another interesting idea I came up, how about adding haptic feedback?

https://docs.expo.dev/versions/latest/sdk/haptics/


You can turn it on with properties like this.

```tsx
        <WheelPickerExpo
          backgroundColor="#202124"
          selectedStyle={styles.selectedStyle2}
          height={300}
          width={150}
          initialSelectedIndex={3}
          items={CITIES.map((name) => ({ label: name, value: '' }))}
          onChange={({ item }) => setCity(item.label)}
          haptics={true}
        />
```

I implemented it and I feel good.

If you like, I can send a pull request for this.

**Comment by adityamr15** [comment]
> Another interesting idea I came up, how about adding haptic feedback?
> 
> https://docs.expo.dev/versions/latest/sdk/haptics/
> 
> You can turn it on with properties like this.
> 
> ```tsx
>         <WheelPickerExpo
>           backgroundColor="#202124"
>           selectedStyle={styles.selectedStyle2}
>           height={300}
>           width={150}
>           initialSelectedIndex={3}
>           items={CITIES.map((name) => ({ label: name, value: '' }))}
>           onChange={({ item }) => setCity(item.label)}
>           haptics={true}
>         />
> ```
> 
> I implemented it and I feel good.
> 
> If you like, I can send a pull request for this.

Wow, this is great feature, you can send pull request.
For the `onScrollEndDrag` can create pull request and we can discuss in it

**Comment by gomo** [comment]
> For the `onScrollEndDrag` can create pull request and we can discuss in it


About `onScrollEndDrag`, I noticed that it doesn't work as expected because it fires the moment the user releases their finger.

I will think about it some more, so please wait a little.

By the way, I upgraded the example app's Expo SDK to 43 to try `haptic` on a real machine. Is this OK? or
 revert it?
