### ISSUE TITLE
Deprecated dependency expo-haptics 8.4.0 (Unable to resolve module @unimodules/core)

### ISSUE THREAD

**Issue by ghost** [adityamr15/react-native-wheel-picker-expo#8]
I'm using expo for Android and iOS and get this error:

> Unable to resolve module @unimodules/core from [...]\node_modules\expo-haptics\build\Haptics.js: @unimodules/core could not be found within the project or in these directories:
>   node_modules

npm version: 8.5.5
expo version: 5.4.3

I assume the error orrucs due to deprecated dependency `"expo-haptics": "~8.4.0"`, which is using unimodules/core. The latest version of expo-haptics is [11.2.0](https://www.npmjs.com/package/expo-haptics). 

Might you update to new version? Thanks.

**Comment by adityamr15** [comment]
You are right, peer dependencies version is deprecated.
Miss match between the example app and source code.

**Comment by ghost** [comment]
Thanks a lot for your fast response. 

Unfortunately there is an error now, if showing a view with `WheelPickerExpo`:
> TypeError: (0, _expoModulesCore.requireNativeModule) is not a function. (In '(0, _expoModulesCore.requireNativeModule)('ExpoHaptics')', '(0, _expoModulesCore.requireNativeModule)' is undefined)

**Comment by adityamr15** [comment]
> Thanks a lot for your fast response.
> 
> Unfortunately there is an error now, if showing a view with `WheelPickerExpo`:
> 
> > TypeError: (0, _expoModulesCore.requireNativeModule) is not a function. (In '(0, _expoModulesCore.requireNativeModule)('ExpoHaptics')', '(0, _expoModulesCore.requireNativeModule)' is undefined)

not sure how to reproduce, create a snack and I will check it.
which version expo SDK you are using?

**Comment by ghost** [comment]
> Thanks a lot for your fast response.
> 
> Unfortunately there is an error now, if showing a view with `WheelPickerExpo`:
> 
> > TypeError: (0, _expoModulesCore.requireNativeModule) is not a function. (In '(0, _expoModulesCore.requireNativeModule)('ExpoHaptics')', '(0, _expoModulesCore.requireNativeModule)' is undefined)

Using expo SDK 44.0.0.
Cannot reproduce in snack. Seems to be an issue of my application. Thanks.
